version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/dileep/cicd-ubuntu
hooks:
  BeforeInstall:
    - location: scripts/dummy.sh
      timeout: 300
      runas: root


